name: 'Slack List Alert Action'
description: 'Sends a list of messages to a Slack channel.'
author: 'ghkdqhrbals'
branding:
  color: 'blue'
  icon: 'message-circle'

inputs:
  slack-webhook-url:
    description: 'The Slack webhook URL to send messages.'
    required: true
  actor:
    description: 'The GitHub user who triggered the action.'
    required: false
    default: ''
  messages:
    description: 'JSON array of messages to send.'
    required: true
    default: '[]'
  message-title:
    description: 'The title of the Slack message.'
    required: false
    default: 'Slack Alert List'
  color:
    description: 'The color of the message attachment.'
    required: false
    default: '#3bb143'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
    ACTOR: ${{ inputs.actor }}
    MESSAGES: ${{ inputs.messages }}
    MESSAGE_TITLE: ${{ inputs.message-title }}
    COLOR: ${{ inputs.color }}