name: Test Action

on:
  workflow_dispatch: # 수동 실행 트리거
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ACTOR: ${{ github.actor }}
          MESSAGES: '["test1", "test2", "test3"]'
          MESSAGE_TITLE: 'Testing Slack Notification Header'
          COLOR: '#3bb143'
        run: |
          python main.py
